#!/bin/bash

### bashdoc [ "-"SECTION ] FILES ... Usage:help
#
# Provide the files you want to print the internal documentation for.
#
# By default, prints the "bbuild" documentation sections.
#
# To print just the `api` sections, call
#
#   bashdoc -api ...
#
# To list just available modules, simply run `bashdoc` on its own
#
###/doc

#%include std/autohelp.sh
#%include std/out.sh
#%include std/searchpaths.sh
#%include std/runmain.sh

list_modules() {
    local thepath f
    out:info "Available modules: "

    while read thepath; do
        out:warn "Checking $thepath"
        while read f; do
            if [[ -f "$thepath/$f" ]]; then
                echo "$f"
            fi
        done < <(ls "$thepath") | column
    done < <(echo "$BBPATH"|sed 's/:/\n/g')
}

main() {
    autohelp:check "$@"

    if [[ -z "$*" ]]; then
        list_modules
        exit 0
    fi

    # ====================================================================
    # Get the section, if specified.

    SECTION='bbuild'

    if [[ "${1:0:1}" = "-" ]]; then
        SECTION="${1:1}"
        shift
    fi

    out:info "Seeking section [$SECTION] on all files."

    print_from "$@"
}

print_from() {
    # =================
    # Process files

    for file in "$@"; do
        if [[ ! -f "$file" ]]; then
            fullpath="$(searchpaths:file_from "$BBPATH" "$file")"
            if [[ -n "$fullpath" ]]; then
                file="$fullpath"
            fi
        fi

        if [[ ! -f "$file" ]]; then
            out:warn "No such file [$file]"
            continue
        fi

        egrep '^##bash-libs:' "$file"

        # Also print the tags for info
        egrep '^#%bbtags' "$file"

        autohelp:print "$SECTION" "$file"
    done
}

runmain bashdoc main "$@"
