#!/usr/bin/env bash

set -euo pipefail

### Bash Builder Runner Usage:help
#
# Run a Bash Builder script directly without pre-compiling.
#
# Suitable for use with a shebang line.
#
#   bbrun SCRIPT SCRIPT_ARGS ...
#
# bbrun uses a temp file in ~/.local/tmp with the same name as
#  the original script.
#
# When the compiled script is run, an environment variable
#  `BBRUN_SCRIPT` contains the path of the original script (use this
#  instead of $0).
#
# Set environment variable `DEBUG_mode=true` to see the BBPATH and build target
#
###/doc

BBRUN_VERSION=1.2

#%include std/syntax-extensions.sh
#%include std/abspath.sh
#%include std/debug.sh
#%include std/colours.sh
#%include std/autohelp.sh

removebuilt() {
    rm "$BUILTSCR" "$BUILDMESSAGES"
}

rewrite_shebang() {
    sed -r -e '1 s|^#!.+$|#!/usr/bin/env bash|g' -i "$BUILTSCR"

    debug:print "Shebang: $(head -n 1 "$BUILTSCR")"
}

check_build_failure() {
    if [[ "$1" != 0 ]]; then
        echo -n "$CRED"
        cat "$BUILDMESSAGES"
        echo -n "$CDEF"

        exit 1
    fi
}

make_private_script() {
    touch "$BUILTSCR"
    chmod 700 "$BUILTSCR"
}

$%function bbrun:main(bbscript) {
    local tempscr build_result BBRUN_SCRIPT
    build_result=0

    tmpdir="$HOME/.local/tmp"

    [[ -e "$tmpdir" ]] ||
        mkdir -p "$tmpdir"

    # Use absolute path so that built script is callable predictably
    export BBRUN_SCRIPT="$(abspath:path "$bbscript")"
    BUILTSCR="$tmpdir/$(basename "$bbscript")"

    ([[ -e "$BBRUN_SCRIPT" ]] && [[ ! -d "$BBRUN_SCRIPT" ]]) || out:fail "'$bbscript' is not a file."

    make_private_script

    BUILDMESSAGES="$(mktemp)"

    debug:print "Building dynamically | BBPATH => $BBPATH"
    debug:print "Building to [$BUILTSCR]"

    bbuild "$bbscript" "$BUILTSCR" &> "$BUILDMESSAGES" || build_result=$?

    chmod 700 "$BUILTSCR" # re-apply the perms, because bbuild will set 755 as part of the build

    trap removebuilt exit
    check_build_failure "$build_result"

    rewrite_shebang
    "$BUILTSCR" "$@"
}

autohelp:check-or-null "$@"
bbrun:main "$@"
